In [4]:
from keras.layers import TextVectorization

## Create a Corpus

In [40]:
corpus = ["I like my brother.",
          "Go to Home!",
          "Do you like my brother?"]

## Adapt a vectorizer on our corpus

In [48]:
text_vectorizer = TextVectorization(ngrams=2)
text_vectorizer.adapt(corpus)

In [49]:
vocab = text_vectorizer.get_vocabulary()
vocab

['',
 '[UNK]',
 np.str_('my brother'),
 np.str_('my'),
 np.str_('like my'),
 np.str_('like'),
 np.str_('brother'),
 np.str_('you like'),
 np.str_('you'),
 np.str_('to home'),
 np.str_('to'),
 np.str_('i like'),
 np.str_('i'),
 np.str_('home'),
 np.str_('go to'),
 np.str_('go'),
 np.str_('do you'),
 np.str_('do')]

In [50]:
for i, word in enumerate(vocab):
    print(f'{word:<9}: {i}')

         : 0
[UNK]    : 1
my brother: 2
my       : 3
like my  : 4
like     : 5
brother  : 6
you like : 7
you      : 8
to home  : 9
to       : 10
i like   : 11
i        : 12
home     : 13
go to    : 14
go       : 15
do you   : 16
do       : 17


## Create sequence vectors of our corpus

In [51]:
encoded_sequences = text_vectorizer(corpus)
print(encoded_sequences)

tf.Tensor(
[[12  5  3  6 11  4  2  0  0]
 [15 10 13 14  9  0  0  0  0]
 [17  8  5  3  6 16  7  4  2]], shape=(3, 9), dtype=int64)


In [52]:
encoded_sequences.numpy()

array([[12,  5,  3,  6, 11,  4,  2,  0,  0],
       [15, 10, 13, 14,  9,  0,  0,  0,  0],
       [17,  8,  5,  3,  6, 16,  7,  4,  2]])

## Test on new sequence

In [53]:
encoded_test = text_vectorizer(['I like my sister'])
print(encoded_test)

tf.Tensor([[12  5  3  1 11  4  1]], shape=(1, 7), dtype=int64)
